name: Build ScannerApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name parikhshit_scanner ScannerApp.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: parikhshit_scanner-${{ matrix.os }}
          path: dist/
