name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Purge pip cache
        run: |
          pip cache purge || true

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist

      - name: Normalize wheel filenames
        run: |
          cd dist
          for f in *.whl; do
            newname=$(echo "$f" | sed 's/__/_/g')
            if [ "$f" != "$newname" ]; then
              echo "Renaming $f → $newname"
              mv "$f" "$newname"
            fi
          done

      - name: Install package
        run: |
          pip install --no-cache-dir dist/*.whl

      - name: Run tests
        run: |
          pytest -v || echo "No tests found"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
